# Form implementation generated from reading ui file '/home/anocweb/Source/apt-qt6-manager/src/ui/about_panel.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AboutPanel(object):
    def setupUi(self, AboutPanel):
        AboutPanel.setObjectName("AboutPanel")
        AboutPanel.resize(750, 600)
        self.aboutLayout = QtWidgets.QVBoxLayout(AboutPanel)
        self.aboutLayout.setSpacing(0)
        self.aboutLayout.setObjectName("aboutLayout")
        self.aboutContent = QtWidgets.QLabel(parent=AboutPanel)
        self.aboutContent.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.aboutContent.setObjectName("aboutContent")
        self.aboutLayout.addWidget(self.aboutContent)

        self.retranslateUi(AboutPanel)
        QtCore.QMetaObject.connectSlotsByName(AboutPanel)

    def retranslateUi(self, AboutPanel):
        _translate = QtCore.QCoreApplication.translate
        self.aboutContent.setText(_translate("AboutPanel", "A modern package manager for Linux systems\\nVersion 1.0"))
