# Form implementation generated from reading ui file 'category_list_panel.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CategoryListPanel(object):
    def setupUi(self, CategoryListPanel):
        CategoryListPanel.setObjectName("CategoryListPanel")
        CategoryListPanel.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(CategoryListPanel)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.categoryTree = QtWidgets.QTreeWidget(parent=CategoryListPanel)
        self.categoryTree.setHeaderHidden(True)
        self.categoryTree.setRootIsDecorated(True)
        self.categoryTree.setItemsExpandable(True)
        self.categoryTree.setExpandsOnDoubleClick(True)
        self.categoryTree.setObjectName("categoryTree")
        self.verticalLayout.addWidget(self.categoryTree)

        self.retranslateUi(CategoryListPanel)
        QtCore.QMetaObject.connectSlotsByName(CategoryListPanel)

    def retranslateUi(self, CategoryListPanel):
        _translate = QtCore.QCoreApplication.translate
        CategoryListPanel.setWindowTitle(_translate("CategoryListPanel", "Category List"))
        self.categoryTree.headerItem().setText(0, _translate("CategoryListPanel", "Categories"))
