# Form implementation generated from reading ui file '/home/anocweb/Source/apt-qt6-manager/src/ui/category_panel.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CategoryPanel(object):
    def setupUi(self, CategoryPanel):
        CategoryPanel.setObjectName("CategoryPanel")
        CategoryPanel.resize(750, 600)
        self.categoryLayout = QtWidgets.QVBoxLayout(CategoryPanel)
        self.categoryLayout.setSpacing(0)
        self.categoryLayout.setObjectName("categoryLayout")
        self.categoryScrollArea = QtWidgets.QScrollArea(parent=CategoryPanel)
        self.categoryScrollArea.setWidgetResizable(True)
        self.categoryScrollArea.setObjectName("categoryScrollArea")
        self.categoryContainer = QtWidgets.QWidget()
        self.categoryContainer.setGeometry(QtCore.QRect(0, 0, 782, 69))
        self.categoryContainer.setObjectName("categoryContainer")
        self.categoryScrollArea.setWidget(self.categoryContainer)
        self.categoryLayout.addWidget(self.categoryScrollArea)

        self.retranslateUi(CategoryPanel)
        QtCore.QMetaObject.connectSlotsByName(CategoryPanel)

    def retranslateUi(self, CategoryPanel):
        pass
