# Form implementation generated from reading ui file 'category_panel.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CategoryPanel(object):
    def setupUi(self, CategoryPanel):
        CategoryPanel.setObjectName("CategoryPanel")
        CategoryPanel.resize(750, 600)
        self.categoryLayout = QtWidgets.QVBoxLayout(CategoryPanel)
        self.categoryLayout.setContentsMargins(0, 0, 0, 0)
        self.categoryLayout.setSpacing(0)
        self.categoryLayout.setObjectName("categoryLayout")
        self.categoryScrollArea = QtWidgets.QScrollArea(parent=CategoryPanel)
        self.categoryScrollArea.setWidgetResizable(True)
        self.categoryScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.categoryScrollArea.setObjectName("categoryScrollArea")
        self.categoryContainer = QtWidgets.QWidget()
        self.categoryContainer.setGeometry(QtCore.QRect(0, 0, 750, 600))
        self.categoryContainer.setObjectName("categoryContainer")
        self.packageListLayout = QtWidgets.QVBoxLayout(self.categoryContainer)
        self.packageListLayout.setContentsMargins(10, 10, 10, 10)
        self.packageListLayout.setSpacing(2)
        self.packageListLayout.setObjectName("packageListLayout")
        self.categoryScrollArea.setWidget(self.categoryContainer)
        self.categoryLayout.addWidget(self.categoryScrollArea)

        self.retranslateUi(CategoryPanel)
        QtCore.QMetaObject.connectSlotsByName(CategoryPanel)

    def retranslateUi(self, CategoryPanel):
        pass
