# Form implementation generated from reading ui file '/home/anocweb/Source/apt-qt6-manager/src/ui/installed_list_item.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_InstalledListItem(object):
    def setupUi(self, InstalledListItem):
        InstalledListItem.setObjectName("InstalledListItem")
        InstalledListItem.resize(714, 125)
        InstalledListItem.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.mainLayout = QtWidgets.QHBoxLayout(InstalledListItem)
        self.mainLayout.setSpacing(12)
        self.mainLayout.setObjectName("mainLayout")
        self.iconLabel = QtWidgets.QLabel(parent=InstalledListItem)
        self.iconLabel.setMinimumSize(QtCore.QSize(64, 64))
        self.iconLabel.setMaximumSize(QtCore.QSize(64, 64))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.iconLabel.setFont(font)
        self.iconLabel.setStyleSheet("background-color: palette(button); border-radius: 8px;")
        self.iconLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.iconLabel.setObjectName("iconLabel")
        self.mainLayout.addWidget(self.iconLabel)
        self.contentLayout = QtWidgets.QVBoxLayout()
        self.contentLayout.setContentsMargins(2, 2, 2, 2)
        self.contentLayout.setSpacing(0)
        self.contentLayout.setObjectName("contentLayout")
        self.nameLabel = QtWidgets.QLabel(parent=InstalledListItem)
        self.nameLabel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.nameLabel.setFont(font)
        self.nameLabel.setStyleSheet("color: palette(window-text); background: transparent; border: none; padding: 0px;")
        self.nameLabel.setObjectName("nameLabel")
        self.contentLayout.addWidget(self.nameLabel, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.descLabel = QtWidgets.QLabel(parent=InstalledListItem)
        self.descLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.descLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.descLabel.setFont(font)
        self.descLabel.setStyleSheet("color: palette(window-text); background: transparent; border: none; padding: 0px;")
        self.descLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        self.descLabel.setWordWrap(True)
        self.descLabel.setObjectName("descLabel")
        self.contentLayout.addWidget(self.descLabel, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.infoLabel = QtWidgets.QLabel(parent=InstalledListItem)
        self.infoLabel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.infoLabel.setFont(font)
        self.infoLabel.setStyleSheet("background: transparent; border: none; padding: 0px;")
        self.infoLabel.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.infoLabel.setObjectName("infoLabel")
        self.contentLayout.addWidget(self.infoLabel, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignBottom)
        self.mainLayout.addLayout(self.contentLayout)
        self.rightLayout = QtWidgets.QVBoxLayout()
        self.rightLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.rightLayout.setObjectName("rightLayout")
        self.backendLabel = QtWidgets.QLabel(parent=InstalledListItem)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.backendLabel.setFont(font)
        self.backendLabel.setStyleSheet("color: palette(window-text); background: transparent; border: none; padding: 2px;")
        self.backendLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.backendLabel.setObjectName("backendLabel")
        self.rightLayout.addWidget(self.backendLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.rightLayout.addItem(spacerItem)
        self.removeButton = QtWidgets.QPushButton(parent=InstalledListItem)
        self.removeButton.setMinimumSize(QtCore.QSize(80, 32))
        self.removeButton.setMaximumSize(QtCore.QSize(80, 32))
        font = QtGui.QFont()
        font.setBold(True)
        self.removeButton.setFont(font)
        self.removeButton.setStyleSheet("QPushButton {\n"
"    background-color: #FF6B6B;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF5252;\n"
"}")
        self.removeButton.setObjectName("removeButton")
        self.rightLayout.addWidget(self.removeButton)
        self.mainLayout.addLayout(self.rightLayout)

        self.retranslateUi(InstalledListItem)
        QtCore.QMetaObject.connectSlotsByName(InstalledListItem)

    def retranslateUi(self, InstalledListItem):
        _translate = QtCore.QCoreApplication.translate
        self.iconLabel.setText(_translate("InstalledListItem", "📦"))
        self.nameLabel.setText(_translate("InstalledListItem", "Package Name"))
        self.descLabel.setText(_translate("InstalledListItem", "Package description text that may wrap to multiple lines"))
        self.infoLabel.setText(_translate("InstalledListItem", "Version 1.0.0 • 50 MB"))
        self.backendLabel.setText(_translate("InstalledListItem", "APT"))
        self.removeButton.setText(_translate("InstalledListItem", "🗑 Remove"))
