# Form implementation generated from reading ui file 'package_list_item.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PackageListItem(object):
    def setupUi(self, PackageListItem):
        PackageListItem.setObjectName("PackageListItem")
        PackageListItem.resize(714, 125)
        PackageListItem.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.mainLayout = QtWidgets.QHBoxLayout(PackageListItem)
        self.mainLayout.setSpacing(12)
        self.mainLayout.setObjectName("mainLayout")
        self.iconLabel = QtWidgets.QLabel(parent=PackageListItem)
        self.iconLabel.setMinimumSize(QtCore.QSize(48, 48))
        self.iconLabel.setMaximumSize(QtCore.QSize(64, 64))
        self.iconLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.iconLabel.setObjectName("iconLabel")
        self.mainLayout.addWidget(self.iconLabel)
        self.contentLayout = QtWidgets.QVBoxLayout()
        self.contentLayout.setContentsMargins(2, 2, 2, 2)
        self.contentLayout.setSpacing(0)
        self.contentLayout.setObjectName("contentLayout")
        self.nameLabel = QtWidgets.QLabel(parent=PackageListItem)
        self.nameLabel.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.contentLayout.addWidget(self.nameLabel)
        self.descLabel = QtWidgets.QLabel(parent=PackageListItem)
        self.descLabel.setMinimumSize(QtCore.QSize(0, 36))
        self.descLabel.setMaximumSize(QtCore.QSize(16777215, 36))
        self.descLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        self.descLabel.setWordWrap(True)
        self.descLabel.setObjectName("descLabel")
        self.contentLayout.addWidget(self.descLabel)
        self.ratingLabel = QtWidgets.QLabel(parent=PackageListItem)
        self.ratingLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.ratingLabel.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.ratingLabel.setObjectName("ratingLabel")
        self.contentLayout.addWidget(self.ratingLabel)
        self.mainLayout.addLayout(self.contentLayout)
        self.rightLayout = QtWidgets.QVBoxLayout()
        self.rightLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.rightLayout.setObjectName("rightLayout")
        self.backendLabel = QtWidgets.QLabel(parent=PackageListItem)
        self.backendLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.backendLabel.setObjectName("backendLabel")
        self.rightLayout.addWidget(self.backendLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.rightLayout.addItem(spacerItem)
        self.installButton = QtWidgets.QPushButton(parent=PackageListItem)
        self.installButton.setMinimumSize(QtCore.QSize(80, 32))
        self.installButton.setMaximumSize(QtCore.QSize(80, 32))
        self.installButton.setObjectName("installButton")
        self.rightLayout.addWidget(self.installButton)
        self.mainLayout.addLayout(self.rightLayout)

        self.retranslateUi(PackageListItem)
        QtCore.QMetaObject.connectSlotsByName(PackageListItem)

    def retranslateUi(self, PackageListItem):
        _translate = QtCore.QCoreApplication.translate
        PackageListItem.setProperty("PackageId", _translate("PackageListItem", "com.package.name"))
        self.iconLabel.setText(_translate("PackageListItem", "📦"))
        self.nameLabel.setText(_translate("PackageListItem", "Package Name"))
        self.descLabel.setText(_translate("PackageListItem", "Package description text that may wrap to multiple lines"))
        self.ratingLabel.setText(_translate("PackageListItem", "★★★★☆ 4.2 (123 reviews)"))
        self.backendLabel.setText(_translate("PackageListItem", "APT"))
        self.installButton.setText(_translate("PackageListItem", "⬇ Install"))
