# Form implementation generated from reading ui file '/home/anocweb/Source/apt-qt6-manager/src/ui/settings_panel.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingsPanel(object):
    def setupUi(self, SettingsPanel):
        SettingsPanel.setObjectName("SettingsPanel")
        SettingsPanel.resize(750, 600)
        self.settingsLayout = QtWidgets.QVBoxLayout(SettingsPanel)
        self.settingsLayout.setSpacing(0)
        self.settingsLayout.setObjectName("settingsLayout")
        self.settingsContent = QtWidgets.QLabel(parent=SettingsPanel)
        self.settingsContent.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.settingsContent.setObjectName("settingsContent")
        self.settingsLayout.addWidget(self.settingsContent)

        self.retranslateUi(SettingsPanel)
        QtCore.QMetaObject.connectSlotsByName(SettingsPanel)

    def retranslateUi(self, SettingsPanel):
        _translate = QtCore.QCoreApplication.translate
        self.settingsContent.setText(_translate("SettingsPanel", "Settings panel coming soon..."))
