# Form implementation generated from reading ui file '/home/anocweb/Source/apt-qt6-manager/src/ui/updates_panel.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UpdatesPanel(object):
    def setupUi(self, UpdatesPanel):
        UpdatesPanel.setObjectName("UpdatesPanel")
        UpdatesPanel.resize(750, 600)
        self.updatesLayout = QtWidgets.QVBoxLayout(UpdatesPanel)
        self.updatesLayout.setContentsMargins(0, 0, 0, 0)
        self.updatesLayout.setSpacing(0)
        self.updatesLayout.setObjectName("updatesLayout")
        self.updatesScrollArea = QtWidgets.QScrollArea(parent=UpdatesPanel)
        self.updatesScrollArea.setWidgetResizable(True)
        self.updatesScrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.updatesScrollArea.setObjectName("updatesScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 750, 600))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.updatesContainerLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.updatesContainerLayout.setContentsMargins(0, 0, 0, 0)
        self.updatesContainerLayout.setSpacing(0)
        self.updatesContainerLayout.setObjectName("updatesContainerLayout")
        self.updatesScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.updatesLayout.addWidget(self.updatesScrollArea)

        self.retranslateUi(UpdatesPanel)
        QtCore.QMetaObject.connectSlotsByName(UpdatesPanel)

    def retranslateUi(self, UpdatesPanel):
        pass
