# Form implementation generated from reading ui file '/home/anocweb/Source/apt-qt6-manager/src/ui/updates_panel.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UpdatesPanel(object):
    def setupUi(self, UpdatesPanel):
        UpdatesPanel.setObjectName("UpdatesPanel")
        UpdatesPanel.resize(750, 600)
        self.updatesLayout = QtWidgets.QVBoxLayout(UpdatesPanel)
        self.updatesLayout.setSpacing(0)
        self.updatesLayout.setObjectName("updatesLayout")
        self.updatesContent = QtWidgets.QLabel(parent=UpdatesPanel)
        self.updatesContent.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.updatesContent.setObjectName("updatesContent")
        self.updatesLayout.addWidget(self.updatesContent)

        self.retranslateUi(UpdatesPanel)
        QtCore.QMetaObject.connectSlotsByName(UpdatesPanel)

    def retranslateUi(self, UpdatesPanel):
        _translate = QtCore.QCoreApplication.translate
        self.updatesContent.setText(_translate("UpdatesPanel", "No updates available"))
