#!/bin/sh
set -e

case "$1" in
    configure)
        # Enable and start the update daemon
        if [ -d /run/systemd/system ]; then
            systemctl daemon-reload || true
            systemctl enable apt-ex-update-checker.service || true
            systemctl start apt-ex-update-checker.service || true
        fi
        ;;
esac

#DEBHELPER#

exit 0
