#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        # Stop and disable the update daemon
        if [ -d /run/systemd/system ]; then
            systemctl stop apt-ex-update-checker.service || true
            systemctl disable apt-ex-update-checker.service || true
        fi
        ;;
esac

#DEBHELPER#

exit 0
