#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        # Stop and disable the update daemon
        if [ -d /run/systemd/system ]; then
            systemctl stop apt-ex-update-checker.service || true
            systemctl disable apt-ex-update-checker.service || true
        fi
        ;;
esac

# Automatically added by dh_installsystemd/13.24.2ubuntu1
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'apt-ex-update-checker.service' >/dev/null || true
fi
# End automatically added section

# Automatically added by dh_python3
if command -v py3clean >/dev/null 2>&1; then
	py3clean -p apt-ex-package-manager 
else
	dpkg -L apt-ex-package-manager | sed -En -e '/^(.*)\/(.+)\.py$/s,,rm "\1/__pycache__/\2".*,e'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section


exit 0
