# Form implementation generated from reading ui file '/home/anocweb/Source/apt-qt6-manager/src/ui/panels/home_panel.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HomePanel(object):
    def setupUi(self, HomePanel):
        HomePanel.setObjectName("HomePanel")
        HomePanel.resize(750, 600)
        self.homeLayout = QtWidgets.QVBoxLayout(HomePanel)
        self.homeLayout.setObjectName("homeLayout")
        self.search_input = QtWidgets.QLineEdit(parent=HomePanel)
        self.search_input.setObjectName("search_input")
        self.homeLayout.addWidget(self.search_input)
        self.package_scroll_area = QtWidgets.QScrollArea(parent=HomePanel)
        self.package_scroll_area.setWidgetResizable(True)
        self.package_scroll_area.setObjectName("package_scroll_area")
        self.package_container = QtWidgets.QWidget()
        self.package_container.setGeometry(QtCore.QRect(0, 0, 782, 69))
        self.package_container.setObjectName("package_container")
        self.package_scroll_area.setWidget(self.package_container)
        self.homeLayout.addWidget(self.package_scroll_area)

        self.retranslateUi(HomePanel)
        QtCore.QMetaObject.connectSlotsByName(HomePanel)

    def retranslateUi(self, HomePanel):
        _translate = QtCore.QCoreApplication.translate
        self.search_input.setPlaceholderText(_translate("HomePanel", "Search packages..."))
