# Form implementation generated from reading ui file '/home/anocweb/Source/apt-qt6-manager/src/ui/panels/installed_panel.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_InstalledPanel(object):
    def setupUi(self, InstalledPanel):
        InstalledPanel.setObjectName("InstalledPanel")
        InstalledPanel.resize(750, 600)
        self.installedLayout = QtWidgets.QVBoxLayout(InstalledPanel)
        self.installedLayout.setSpacing(0)
        self.installedLayout.setObjectName("installedLayout")
        self.installedScrollArea = QtWidgets.QScrollArea(parent=InstalledPanel)
        self.installedScrollArea.setWidgetResizable(True)
        self.installedScrollArea.setObjectName("installedScrollArea")
        self.installedContainer = QtWidgets.QWidget()
        self.installedContainer.setGeometry(QtCore.QRect(0, 0, 782, 69))
        self.installedContainer.setObjectName("installedContainer")
        self.installedScrollArea.setWidget(self.installedContainer)
        self.installedLayout.addWidget(self.installedScrollArea)

        self.retranslateUi(InstalledPanel)
        QtCore.QMetaObject.connectSlotsByName(InstalledPanel)

    def retranslateUi(self, InstalledPanel):
        pass
